var showMenu=!0,html5=!0,subtractBy=0,gecko=!1,player,stopTime;function stopNow(){timeID=0;player.pause();playing=!1;speakingQuiz&&setTimeout(selectNextSpeakingQuizElement,1500)}function seekEvent(){player.play();timeID=setTimeout(stopNow,stopTime)}
function setPlayerVariable(){(player=document.getElementsByTagName("audio")[0])||(player=document.getElementsByTagName("video")[0]);player&&(navigator.userAgent.indexOf("AppleWebKit")!==-1?(slowSeek=!0,player.addEventListener("seeked",seekEvent,!1)):navigator.userAgent.indexOf("Firefox")!=-1&&(slowSeek=!0,player.addEventListener("seeked",seekEvent,!1),gecko=!0),player.play(),player.readyState>3?(stopAt(times[0]-0.1),loadedVar=!0):player.addEventListener("playing",function(){loadedVar||(stopAt(times[0]-
0.1),loadedVar=!0)},!0))}function setStopper(b){stopTime=b}function stopNow2(){timeID=0;player2.pause();playing=!1}function playAt(b){player.currentTime=b;slowSeek||player.play()}function playAt2(b){player2.currentTime=b}function play(){player.play()};var originalArray,timeIndexes,currentIndex,missed=0,timesIndex=-1,oldIndex=-2,id,timeID,slowSeek=!1,loadedVar=!1,delay=1500,translationId=null;function stopNowRandom(){stopNow();quiz||(timeID=setTimeout(randomGenerator,delay*1E3))}function stopAt(b){timeID!=0&&window.clearTimeout(timeID);b*=1E3;timeID=setTimeout(stopNow,b)}function getName(b){return ie?b.srcElement.name:b.target.getAttribute("name")}
function clickOccurred(b,c){var d=getId(b);if(quiz)guess(b,d);else if(showMenu){var e='<ul><li><a href="javascript:saveItem()">Save to account<br/> '+getTextToDisplay(d,!0,c)+keyPressInfo+"</a></li></ul>",f=document.getElementById("context_menu");f.innerHTML=e;f.style.visibility="visible";svg?positionsvg(b,f,2,2):(menuId=getName(b),document.getElementById(d).getAttribute("name"),position(b,f,2,2));b.cancelBubble=!0;b.stopPropagation&&b.stopPropagation()}}var quiz=!1,menuId;
function getId(b){var c;c=ie?b.srcElement.id:b.target.id;c==""&&(c=ie&&!html5?b.srcElement.parent.id:b.target.parentNode.id);if(c.indexOf("b")!=-1)return c.substr(0,c.length-1);return c}var messageDisplayed=!1,messageDiv;
function displayMessage(b,c){messageDisplayed?messageDiv=document.getElementById("message"):(messageDiv=document.createElement("div"),messageDiv.setAttribute("id","message"),document.body.appendChild(messageDiv),messageDisplayed=!0);messageDiv.innerHTML=b;messageDiv.style.visibility="visible";setTimeout(hideMessage,c)}function hideMessage(){messageDiv.style.visibility="hidden"}var lockedID,locked=!1;function unlock(){locked=!1;lockedID=-1}var hidePopupMode=!1;
function playSegment(b,c){playSoundSegment(times[b],times[c])}function playAndShow(b,c){if(!quiz){var d=getId(b);playAndShowId(b,d,c)}}function playAndShowParent(b,c){if(!quiz){var d=getParentId(b);playAndShowId(b,d,c)}}var timeIndex=-1;
function playAndShowId(b,c,d){var e=new Number(c),f=times[e];if(f!=-1){if(!locked||timeIndex!=e)timeIndex=e,locked=!0,lockedID=setTimeout(unlock,300),e=times[timeIndex+1],e==-1&&(e=getNextTime(timeIndex+2)),playSoundSegment(f,e);hidePopupMode&&(d=!1);if(d)d=document.getElementById("A"+c),f=d.innerHTML,e=d.getAttribute("grammar"),showTranslation&&(d=document.getElementById("T"+c),d!=null&&(f=f+"<br /><em>("+d.innerHTML+")</em>")),showtip(b,f,e)}}
function getNextTime(b){for(var c=times[b];c==-1&&b<times.length;)b++,c=times[b];return c}function computeAndGetTranslation(b){b=Number(b);if(typeof translationMap!=="undefined"){var c=translationMap.length;for(i=0;i<c;i++)if(translationMap[i].id===b)return translationId=translationMap[i].tId,document.getElementById("T"+translationId)}translationId=b+1;return document.getElementById("T"+translationId)}
function getTextToDisplay(b,c,d){var d=d?document.getElementById(b):document.getElementById("A"+b),e=d.innerHTML;c&&(d=document.getElementById("T"+b),d==null&&(d=computeAndGetTranslation(b)),e=e+" <em>("+d.innerHTML+")</em>");return e}var showTranslation=!1;function set(){}function setDivs(){var b=document.getElementsByTagName("div");if(b){for(var c=[],d=0,e=0;e!=b.length;e++)b[e].getAttribute("class")=="pictorial"&&(c[d]=b[e],d++);processElements(c)}}
function processElements(b){for(var c=0;c!=b.length;c++)ie&&!html5?(b[c].onmouseover=function(){playAndShow(event,!0)},b[c].onclick=function(){clickOccurred(event,!1)}):(b[c].onmouseover=function(b){playAndShow(b,!0)},b[c].onclick=function(b){clickOccurred(b,!1)}),b[c].onmouseout=function(){popDown()}}
function processElement(b){ie&&!html5?(b.onmouseover=function(){playAndShow(event,!0)},b.onclick=function(){clickOccurred(event,!1)}):(b.addEventListener("mouseover",function(b){playAndShow(b,!0)},!1),b.onclick=function(b){clickOccurred(b,!1)},b.onmousemove=positiontip);b.onmouseout=function(){popDown()}}
function processHoverElement(b){ie&&!html5?(b.onmouseover=function(){playAndShow(event,!1)},b.onclick=function(){clickOccurred(event,!0)}):(b.onmouseover=function(b){playAndShow(b,!1)},b.onclick=function(b){clickOccurred(b,!0)});b.onmouseout=function(){popDown()}}function processByClass(){if(document.getElementsByClassName){var b=document.getElementsByClassName("audio");if(b)for(var c=0;c!=b.length;c++)processHoverElement(b[c])}}
function ietruebody(){return document.compatMode&&document.compatMode!="BackCompat"?document.documentElement:document.body}function popDown(){if(tip!=null)tip.style.visibility="hidden",showing=!1}var keyPressInfo="";function keyListener(b){if(ie)b=window.event;b.keyCode==113?toggleQuiz():b.keyCode==104?toggleLabels():b.keyCode==98?activeBeginnersMode(!0):b.keyCode==105?activeIntermediateMode(!0):b.keyCode==97&&activeAdvancedMode(!0)}var currentDifficulty=2;
function activeBeginnersMode(b){b&&setCookie("difficulty","0",365);currentDifficulty==1?subtractDifficulties(i):currentDifficulty==2&&(subtractDifficulties(i),subtractDifficulties(a));currentDifficulty=0}function activeIntermediateMode(b){b&&setCookie("difficulty","1",365);currentDifficulty==0?addDifficulties(i):currentDifficulty==2&&subtractDifficulties(a);currentDifficulty=1}
function activeAdvancedMode(b){b&&setCookie("difficulty","",-1);currentDifficulty==0?(addDifficulties(i),addDifficulties(a)):currentDifficulty==1&&addDifficulties(a);currentDifficulty=2}function addDifficulties(b){var c=0,d=b.length;if(useSvg)for(c=0;c<d;c++)SVGdoc.showIdGroup(b[c]);for(c=0;c<d;c++){var e=document.getElementById(b[c]);if(e!=null)e.style.display="block"}}
function subtractDifficulties(b){var c=0;if(useSvg)for(c=0;c<b.length;c++)SVGdoc.hideIdGroup(b[c]);for(c=0;c<b.length;c++){var d=document.getElementById(b[c]);if(d&&(d.style.display="none",translation=document.getElementById("T"+b[c])))translation.style.display="none"}}
function toggleSpelling(){hidePopupMode=!hidePopupMode;var b=document.getElementById("spelling");hidePopupMode?(b.checked=!1,displayMessage("The spelling won't be shown. Press the 'h' to display it again.",3E3)):(b.checked=!0,displayMessage("The spelling will now be displayed.",3E3))}var tip,ns6,ie,showing=!1,offsetfromcursorX=2,offsetfromcursorY=2;
function showtip(b,c,d){tip=document.getElementById("popup");tip.innerHTML=c;tip.style.visibility="visible";if(d!=null)tip.style.backgroundColor=d=="m"?"#DDDDFF":d=="f"?"#FFDDDD":"#DDFFDD";showing=!0;svg?positiontipsvg(b):position(b,tip,10,20)}function positiontipsvg(b){if(showing)tip.style.top=b.clientY+svgOffsetTop+10+"px",tip.style.left=b.clientX+svgOffsetLeft+20+"px"}function positionsvg(b,c,d,e){c.style.top=b.clientY+svgOffsetTop+d+"px";c.style.left=b.clientX+svgOffsetLeft+e+"px"}
function positiontip(b){showing&&position(b,tip,10,20)}
function position(b,c,d,e){var f=ns6?b.pageX:event.clientX+ietruebody().scrollLeft,h=ns6?b.pageY:event.clientY+ietruebody().scrollTop,j=ie&&!window.opera?ietruebody().clientWidth:window.innerWidth-20,g=ie&&!window.opera?ietruebody().clientHeight:window.innerHeight-20,g=ie&&!window.opera?g-event.clientY-e:g-b.clientY-e;c.style.left=(ie&&!window.opera?j-event.clientX-d:j-b.clientX-d)<c.offsetWidth?f-c.offsetWidth+"px":f<(d<0?d*-1:-1E3)?"5px":f+d+"px";c.style.top=g<c.offsetHeight?h-c.offsetHeight-e+
"px":h+e+"px"}document.onmousemove=positiontip;
(function(b){var c=navigator.userAgent.toLowerCase(),d=navigator.appName=="Microsoft Internet Explorer";html5?document.addEventListener("DOMContentLoaded",b,!1):/webkit/.test(c)?timeout=setTimeout(function(){document.readyState=="loaded"||document.readyState=="complete"?b():setTimeout(arguments.callee,10)},10):!d&&/mozilla/.test(c)&&!/(compatible)/.test(c)||/opera/.test(c)?document.addEventListener("DOMContentLoaded",b,!1):d?(document.write("<script type='text/javascript' id='contentloadtag' defer='defer' src='javascript:void(0)'><\/script>"),document.getElementById("contentloadtag").onreadystatechange=
function(){this.readyState=="complete"&&b()}):window.onload=b})(init);function svgclick(b){if(!quiz){var c=getId(b);menuId=idMappings[parseInt(c)]}clickOccurred(b,!1)}function processAreas(){var b=document.getElementsByTagName("area");if(b)for(var c=0;c!=b.length;c++)processElement(b[c])}function processDivs(){var b=document.getElementsByTagName("div");if(b)for(var c=0;c!=b.length;c++){var d=b[c].getAttributeNode("class");d!=null&&d.nodeValue=="pictorial"&&processElement(b[c])}}
function processLinks(){var b=document.getElementsByTagName("a");if(b)for(var c=0;c!=b.length;c++){var d=b[c].getAttributeNode("class");d!=null&&(d.nodeValue=="hover"?processHoverElement(b[c]):d.nodeValue=="pictorial"&&processElement(b[c]))}}function initVariables(){ie=document.all;ns6=document.getElementById&&!document.all}var hasLinks=!0,hasDivs=!0;
function init(){document.onclick=clicked;initVariables();processAreas();hasDivs&&processDivs();hasLinks&&processLinks();processByClass();setPlayerVariable();document.onkeypress=keyListener;var b=document.getElementById("quiz");if(b!=null&&(b.checked=!1,b=document.getElementById("spelling"),b!=null))b.checked=!0;svg||setDifficulty()}
function setDifficulty(){var b=getCookie("difficulty");if(typeof hasDifficulties!=="undefined"&&hasDifficulties&&b!=null)if(b==0){if(b=document.getElementById("beginner"))b.checked=!0;activeBeginnersMode(!1)}else if(b==1){if(b=document.getElementById("intermediate"))b.checked=!0;activeIntermediateMode(!1)}}var svgOffsetTop,svgOffsetLeft,SVGdoc,svg=!1,showObjects=!0;
function svgInit(b){SVGdoc=b;svg=document.getElementById("svg");svgOffsetTop=svg.offsetTop;svgOffsetLeft=svg.offsetLeft;svg.offsetParent!=null&&(svgOffsetTop=svg.offsetParent.offsetTop+svgOffsetTop,svgOffsetLeft=svg.offsetParent.offsetLeft+svgOffsetLeft);SVGdoc.showObjectsy(showObjects);setDifficulty()}function randomGenerator(){setTimesIndex();var b=times[timesIndex];playAt(b);b=times[letterIndex+1]-b;timeID!=0&&window.clearTimeout(timeID);timeID=setTimeout(stopNowRandom,b*1E3)}
function isActiveSVG(b){if(hasDeactivatedQuizElements&&deactivatedQuizElements.indexOf(b)!=-1)return!1;if(currentDifficulty==1){if(a.indexOf(b)!=-1)return!1}else if(currentDifficulty==0){if(a.indexOf(b)!=-1)return!1;if(i.indexOf(b)!=-1)return!1}return!0}
function isActive(b){if(hasDeactivatedQuizElements&&deactivatedQuizElements.indexOf(b)!=-1)return!1;if(hasDifficulties&&difficulty!=null)if(currentDifficulty==1){if(a.indexOf(b)!=-1)return!1}else if(currentDifficulty==0){if(a.indexOf(b)!=-1)return!1;if(i.indexOf(b)!=-1)return!1}return!0}function updateActiveQuizElements(){var b=[];for(p=0;p<active.length;p++)if(active[p]=="true"){var c=document["group"+p];for(z=0;z<c.length;z++)b.push(times[c[z]])}b.sort()}var activeQuizElements;
function createArrayIndexArray(){var b=times.length,c=[];if(svg)for(y=0;y<b-1;y++){var d=times[y];d!=-1&&isActiveSVG(y)&&c.push(y)}else for(y=0;y<b-1;y++)d=times[y],d!=-1&&isActive(y)&&c.push(y);return c}function playLetter(){playSound(timesIndex)}var quizInited=!1,supportshtml5Audio,soundRoot="/snd/";function initQuizMode(){createAudioElement("quiz_audio");createAudioElement("applause")}
function createAudioElement(b){var c=document.createElement("audio");if(supportshtml5Audio=c.canPlayType)navigator.userAgent.indexOf("Firefox")==-1&&navigator.userAgent.indexOf("Chrome")==-1?c.setAttribute("src",soundRoot+b+".m4a"):c.setAttribute("src",soundRoot+b+".ogg"),c.load(),c.setAttribute("id",b),c.className="pop_up",document.body.appendChild(c)}var ctrldown=!1,_quizModeOn=!1,hover_over_array;function toggleQuizMode(){_quizModeOn?deactivateQuizMode():activateQuizMode()}
function activateQuizMode(){_quizModeOn=!0;hover_over_array=[];var b=document.getElementsByTagName("a");if(b)for(var c=0;c!=b.length;c++){var d=b[c];if(d.getAttribute("class")=="hover")hover_over_array.push(d.innerHTML),d.innerHTML="******"}}function deactivateQuizMode(){_quizModeOn=!1;var b=0,c=document.getElementsByTagName("a");if(c)for(var d=0;d!=c.length;d++){var e=c[d];if(e.getAttribute("class")=="hover")e.innerHTML=hover_over_array[b],b++}}
function toggleQuiz(){if(speakingQuiz)turnOffQuizMode(),document.getElementById("speakingQuiz").checked=!1;var b=document.getElementById("quiz");if(quiz){var c=document.getElementById("speaker");hideElement("quiz_div");c.innerHTML="";quiz=!1;b.checked=!1;displayMessage("Quiz mode has been disactivated",3E3)}else startQuiz(),displayMessage("Quiz mode has been activated. Click on the object that you hear pronounced. Place the object over the speaker to hear the object pronounced again.",4E3),b.checked=
!0,quizInited||(quizInited=!0,setTimeout(initQuizMode,1500))}function hideElement(b){document.getElementById(b).style.visibility="hidden"}var speakerHTML='<a onmouseover="playLetter()"><img id="speaker" src="images/speaker.png" alt="speaker" width="38" height="38" border="0"></a>';
function startQuiz(){var b=document.getElementById("speakingQuiz");if(b!=null&&b.checked)clearQuizTimeout(),b.checked=!1;document.getElementById("speaker").innerHTML=speakerHTML;quiz=!0;originalArray==null&&(originalArray=createArrayIndexArray());timeIndexes=originalArray.reverse();setTimeIndex();playSound(timesIndex);document.getElementById("quiz_div").style.visibility="visible"}
function toggleSpeakingQuiz(){speakingQuiz?turnOffQuizMode():(startSpeakingQuiz(),displayMessage("Speaking quiz mode has been activated. Say the word of the selected object. The voice that follows is a confirmation or correction.",4E3))}function turnOffQuizMode(){quiz=speakingQuiz=!1;deselectSpeakingQuizElement()}function clearQuizTimeout(){timeID!=0&&(window.clearTimeout(timeID),stopNow())}var speakingQuiz=!1;
function startSpeakingQuiz(){speakingQuiz=!0;var b=document.getElementById("quiz");if(b.checked){var c=document.getElementById("speaker");hideElement("quiz_div");c.innerHTML="";b.checked=!1;clearQuizTimeout()}quiz=!0;originalArray==null&&(originalArray=createArrayIndexArray());timeIndexes=originalArray.reverse();selectNextSpeakingQuizElement()}
function deselectSpeakingQuizElement(){if(hasSelectedElement)svg?SVGdoc.hideGuess(timesIndex):speakingQuizSelectedElement.className=previousClassName,hasSelectedElement=!1}var speakingQuizSelectedElement,previousClassName,hasSelectedElement;
function selectNextSpeakingQuizElement(){deselectSpeakingQuizElement();setTimeIndex();removeTime(currentIndex);svg?SVGdoc.guess(timesIndex):(speakingQuizSelectedElement=document.getElementById(timesIndex),previousClassName=speakingQuizSelectedElement.className,speakingQuizSelectedElement.className+=" quiz_selected");hasSelectedElement=!0;setTimeout(playLetter,3E3)}
function setTimeIndex(){var b=timeIndexes.length;if(b!=1&&b==0)missed==0?(displayMessage("Congratulations! You got them all right.",2E3),playAudio("applause")):missed==1?displayMessage("Good! You only missed one. Starting over..",2E3):displayMessage("You missed several. Starting over..",2E3),missed=0,timeIndexes=originalArray.reverse(),b=timeIndexes.length;currentIndex=Math.floor(Math.random()*b);for(timesIndex=timeIndexes[currentIndex];oldIndex==timesIndex&b>1;)currentIndex=Math.floor(Math.random()*
b),timesIndex=timeIndexes[currentIndex];oldIndex=timesIndex}function playLetter(){playSound(timesIndex)}function removeTime(b){var c=timeIndexes.slice(0,b),b=timeIndexes.slice(b+1,timeIndexes.length);timeIndexes=c.concat(b)}function hideCheckmark(){checkmark.style.visibility="hidden"}function hideWrong(){document.getElementById("wrong").style.visibility="hidden"}
function indicateCorrectAnswer(b){var c=document.getElementById("checkmark");c==null&&(c=document.createElement("img"),c.setAttribute("id","checkmark"),c.setAttribute("src","images/green_checkmark.png"),c.setAttribute("style","position:absolute;"),document.body.appendChild(c));c.style.visibility="visible";svg?positionsvg(b,c,-40,-40):position(b,c,-40,-40);setTimeout(hideCheckmark,1E3)}
function indicateIncorrectAnswer(b){var c=document.getElementById("wrong");c==null&&(c=document.createElement("img"),c.setAttribute("id","wrong"),c.setAttribute("src","/images/wrong.png"),c.setAttribute("style","position:absolute;"),document.body.appendChild(c));c.style.visibility="visible";svg?positionsvg(b,c,-40,-40):position(b,c,-40,-40);setTimeout(hideWrong,1E3)}function playAudio(b){if(supportshtml5Audio&&(b=document.getElementById(b),b!=null))b.currentTime=0,b.play()}
function guess(b,c){timesIndex==c?(indicateCorrectAnswer(b),removeTime(currentIndex),setTimeIndex(),playSound(timesIndex)):(playAudio("quiz_audio"),indicateIncorrectAnswer(b),missed++)}function playChain(){}function playSound(b){timeID!=0&&(window.clearTimeout(timeID),stopNow());var c;if(b==-1){if(quiz)return;c=0}else c=times[b];b=getValidEndTime(b)-c;slowSeek?(setStopper(b*1E3),playAt(c)):(playAt(c),timeID=setTimeout(stopNow,b*1E3))}
function getValidEndTime(b){b++;for(var c=times[b++];c==-1&&b<times.length;)c=times[b],b++;return c}function playSoundSegment(b,c){timeID!=0&&(window.clearTimeout(timeID),stopNow());var d=c-b-subtractBy;if(slowSeek){if(gecko){var e=b-player.currentTime;if(e<1&&e>0)player.currentTime=0}setStopper(d*1E3);playAt(b)}else playAt(b),timeID=setTimeout(stopNow,d*1E3)}
function clicked(){var b=document.getElementById("context_menu");if(b.style.visibility=="visible")return b.style.visibility="hidden",!0;if(options!=null&&options.style.visibility=="visible")options.style.visibility="hidden"}function saveItem(){storeWord();document.getElementById("context_menu").style.visibility="hidden"}var req;
function storeWord(){var b="/user/save_word.jsp?target="+target+"&lang="+language+"&id="+menuId;if(translationId!=null){var c=document.getElementById(translationId).name;b+="&translationId="+c;translationId=null}typeof XMLHttpRequest!="undefined"?req=new XMLHttpRequest:window.ActiveXObject&&(req=new ActiveXObject("Microsoft.XMLHTTP"));req.open("GET",b,!0);req.onreadystatechange=callback;req.send(null)}function quizSkip(){removeTime(currentIndex);setTimeIndex();playSound(timesIndex)}
function quizShow(){var b=document.getElementById("A"+timesIndex).innerHTML;displayMessage(b,2E3)}function display(){}function callback(){req.readyState==4&&(req.status==200?req.responseXML!=null&&req.responseXML.getElementsByTagName("message")[0].childNodes[0].nodeValue=="invalid"&&alert("Please login. Click on 'My Account' to get a login prompt."):alert("Please login. Click on 'My Account' to get a login prompt."+req.status))}var options;
function displayOptions(b,c){if(options!=null&&options.style.visibility=="visible")options.style.visibility="hidden";var d;if(ie){if(c==null)c=window.event;d=c.srcElement}else d=c.target;for(var e=0,f=0;d!=null;)e+=d.offsetTop,f+=d.offsetLeft,d=d.offsetParent;options=document.getElementById(b);options.style.top=e;options.style.left=f;options.style.visibility="visible";c.cancelBubble=!0;c.stopPropagation&&c.stopPropagation()}var hasGroups=!1;
function remove(b){if(useDiscreteElements){var b=range(b),c=[];if(b.length==0)for(i=1;i<range.length;i++){b=range[i];for(z=0;z<b.length;z++)value=currentArray[b[z]],c.push(value)}else for(i=start=0;i<b.length;i++){value=b[i];for(z=start;z<value;z++)toSave=currentArray[z],c.push(toSave);start=z+1}currentArray=c}}function addRanges(b,c){for(i=b;i<c;i++)currentArray.push(i)}
function add(b){if(b==0){addRanges(0,range[b]);for(i=0;i<range[b];i++){var c="letter"+i;document.getElementById(c).style.visibility="visible"}}else{start=b==0?0:range[b-1];addRanges(start,range[b]);for(i=start;i<range[b];i++)if(c="letter"+i,!_slideshow)document.getElementById(c).style.visibility="visible"}}active=[];function changeGroup(b){active[b.value]=b.checked?!0:!1;updateActiveQuizElements()}
function setCookie(b,c,d){var e=new Date;e.setDate(e.getDate()+d);c=escape(c)+(d==null?"":"; expires="+e.toUTCString())+"; path=/";document.cookie=b+"="+c}function removeCookie(b){document.cookie=b+"=; expires=Thu, 01-Jan-70 00:00:01 GMT; path=/"}function getCookie(b){var c,d,e,f=document.cookie.split(";");for(c=0;c<f.length;c++)if(d=f[c].substr(0,f[c].indexOf("=")),e=f[c].substr(f[c].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,""),d==b)return unescape(e)}var suggestionExpanded=!1;
function expandSuggestions(){var b=document.getElementById("suggest"),c=document.getElementById("suggestSymbol");suggestionExpanded?(b.style.display="none",suggestionExpanded=!1,c.innerHTML="+"):(suggestionExpanded=!0,b.style.display="block",c.innerHTML="-")};
